[platformio]
default_envs = sender
src_dir = .

[env]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
monitor_speed = 115200

lib_deps =
  jgromes/RadioLib
  fastled/FastLED

build_flags =
  -I include

[env:receiver]
upload_port = COM8
monitor_port = COM8
build_src_filter =
  +<receiver/>
  +<shared/>
  -<sender/>
  -<test/>
  -<.pio/>

[env:sender]
upload_port = COM7
monitor_port = COM7
build_src_filter =
  +<sender/>
  +<shared/>
  -<receiver/>
  -<test/>
  -<.pio/>
